In [1]:
import numpy as np

## The Basic

In [11]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#get dimension
a.ndim

1

In [5]:
#get shape
b.shape

(2, 3)

In [9]:
#get type
a.dtype

dtype('int16')

In [12]:
#get size
a.itemsize

4

In [13]:
#get total size
a.nbytes

12

## Accessing/Changing specific elements, rows, columns, etc.

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# get specific element [row, column]
a[1,5]

np.int64(13)

In [28]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
#get specific column
a[:,2]

array([ 3, 10])

In [32]:
#getting a little more fancy starting [index:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [34]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
#get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [38]:
#replace
b[:,1,1:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [39]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Inititalizing different types of arrays

In [40]:
#all zero matrix

In [44]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
#all ones matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [52]:
#any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [54]:
#any other number full_like
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
#random decimal numbers
np.random.rand(4,2)

array([[0.90686777, 0.68835006],
       [0.95756184, 0.92534796],
       [0.0387803 , 0.15882691],
       [0.99165848, 0.13538116]])

In [60]:
#random integer values
np.random.randint(7, size=(3,3))

array([[3, 2, 0],
       [6, 0, 4],
       [2, 4, 6]], dtype=int32)

In [62]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


## Mathematics

In [77]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [78]:
a+2

array([3, 4, 5, 6])

In [79]:
a-2

array([-1,  0,  1,  2])

In [80]:
a*2

array([2, 4, 6, 8])

In [81]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [82]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [83]:
a**2

array([ 1,  4,  9, 16])

In [84]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [86]:
#take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear algebra

In [96]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics

In [100]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.min(stats, axis=1)

array([1, 4])

In [104]:
np.max(stats)

np.int64(6)

In [113]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing arrays

In [119]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [120]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
#horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## miscelleneous

In [122]:
#load data from file

In [135]:
loaddata = np.genfromtxt('data.txt', delimiter=',')
loaddata

ValueError: Some errors were detected !
    Line #3 (got 17 columns instead of 18)

In [136]:
#boolean masking and advance indexing

loaddata[loaddata > 50]

NameError: name 'loaddata' is not defined

In [138]:
#you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [159]:
#question 1

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,222,23,24,25],
              [26,27,28,29,30]])
print(a)

a[2:4,0:2]



[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21 222  23  24  25]
 [ 26  27  28  29  30]]


array([[11, 12],
       [16, 17]])

In [170]:
#question 2

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,222,23,24,25],
              [26,27,28,29,30]])
print(a)

a[[0,1,2,3],[1,2,3,4]]

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21 222  23  24  25]
 [ 26  27  28  29  30]]


array([ 2,  8, 14, 20])

In [181]:
#question 3

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,222,23,24,25],
              [26,27,28,29,30]])
print(a)

a[[0,4,5],3:]

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21 222  23  24  25]
 [ 26  27  28  29  30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])